### ISSUE TITLE
Q: Why do you distinguish between hyperlinks? 

### ISSUE THREAD

**Issue by filip26** [kevinswiber/siren#14]
I'm curious why do you distinguish between hyperlinks. Siren defines concept of Actions and Links which are booth structures describing a hyperlink + metadata.

Siren defines difference between Action and Link as:
- an action (do something) is not semantically same as a link (go somewhere) 
- an action may contain request body description (e.g. fields) and additional parameters (type, ...)

But, I think that it's not necessarily because a hyperlink is always just a reference on a resource (+metadata) and we can make some presumptions (like if a method is not defined then it's GET, if fields are missing then request body is empty, etc.) to get just one simple hyperlink structure. 

Question:
   How I should map hyperlink supporting GET method and representing a list of users. As a link or an action?

My motivation is to keep learning curve as low as is possible and I think that unification of hyperlink notation can help.

**Comment by xogeny** [comment]
I know this is closed and I don’t want to re-open it, but I just had a comment.

@kevinswiber, I understand your model for data, behavior and relationships and that is largely how I use it.  However, the thing is that you only provide a means of inlining data, not relationships.  As such, any time I want to inline related resources, I end up including them as entities which ends up going against the grain.  You talked about the format helping to identify problems in the API, but this seems like a case (to me, at least) where a the format makes a seemingly legit need (embedded related resources) look like a problem.

Comments?
