### ISSUE TITLE
Headers for Actions

### ISSUE THREAD

**Issue by danielgsims** [kevinswiber/siren#39]
I was wondering how one goes about including required header fields in an action. For example, you might require to authenticate your application using HMAC and use header fields to implement that. What would be a good way to display those required fields in an action?

**Comment by LoZeno** [comment]
I know this is way back from 2014, but I am interested too in having descriptors for header fields in actions: I'm trying to implement Siren in an existing API, and we have one step where after a POST call the user receives a session token to put in the headers of all the following call, then a uniqueID to use in the headers of the third and subsequent actions, and each response contains at least three actions which are identical in URL and params, but give slightly different results depending on what API versioning they put in the headers.
I know I can devise workarounds for all these things, but given they are not just a few maybe it would make a case for header prototypes in actions.
