### ISSUE TITLE
Properties Object should have nested object or arrays

### ISSUE THREAD

**Issue by dev-tim** [kevinswiber/siren#47]
Hi! 
I'm using Siren specification to implement the API in one of the services on the project.
Thus, I have a question regarding spec for the properties object.
Can it include another objects or arrays (I think it should according to http://www.json.org/ specification as it is JSON object).

For example I would like to represent a device which has properties as below:

``` 
 "properties":{  
      "on":true,
      "tags":[  
         "bedroom",
         "night"
      ],
      "color":{  
         "hue":123,
         "saturation":23,
         "brightness":42
      }
   }
```

**Comment by ericelliott** [comment]
I do this all the time. If it's not allowed, I'm in trouble. ;)

**Comment by kevinswiber** [comment]
Yes, `properties` is just a JSON object.

Sent from my iPhone

On Apr 2, 2015, at 5:18 AM, Tim Zadorozhniy <notifications@github.com>
wrote:

Hi!
I'm using Siren specification to implement the API in one of the services
on the project.
Thus, I have a question regarding spec for the properties object.
Can it include another objects or arrays (I think it should according to
http://www.json.org/ specification as it is JSON object).

For example I would like to represent a device which has properties as
below:

 "properties":{
      "on":true,
      "tags":[
         "bedroom",
         "night"
      ],
      "color":{
         "hue":123,
         "saturation":23,
         "brightness":42
      }
   }

—
Reply to this email directly or view it on GitHub
<https://github.com/kevinswiber/siren/issues/47>.

**Comment by mcintyre321** [comment]
Can these property objects have a meaningful 'class' attribute?

**Comment by kevinswiber** [comment]
@mcintyre321 I tie that information into the entity's `class` documentation.

**Comment by apsoto** [comment]
I think this issue can be closed

**Comment by dominicbarnes** [comment]
+1 for closing this
