### ISSUE TITLE
A standard, error response?

### ISSUE THREAD

**Issue by apsoto** [kevinswiber/siren#5]
As I've been writing a client (still in it's infancy) I see a need for possibly defining a basic error type that can provide some more context to the client beyond the HTTP status.

Here's what I've come up with so far:

``` json
  {
    "class":"error",
    "properties": {
      "message":"User 1 not found",
      "status":"not_found",
      "code":404
    }
  }
```

This could easily be extended by API authors with additional properties, actions and links.

Still very early for me with it's usage, but I think there might be a good case for a link or action from this state, but I haven't implemented enough yet to see any patterns emerge.

**Comment by pke** [comment]
I wonder why the errors are an array and not a hash?

```
properties: {
  errors: {
    username: {
       message: "Username is missing",
       type: "missing"
    },
    password: {
      message: "Password must be at least 6 chars",
      type: "length"
    }
  }
}
```

Seems to be better accessible than having the errors in an array. Any reason for using an array, where one has to extract the action field the error relates to by traversing the array multiple times, over a simple field name lookup?

**Comment by apsoto** [comment]
@pke it's been a few years :) . 

I see very little difference between a hash or an array.  It seems to be how you prefer to access it.

A hash requires out of band knowledge of the keys to look up directly, but TBH, you can iterate both data structures and pull the keyname, so it's a minor argument in favor of an array IMO

**Comment by winston0410** [comment]
I used to thought that Siren doesn't provide a way to present error yet I am wrong. It will be great if the above discussion can be translated into a standard and documented, so there will not be reinventing wheel by devs who is using siren.
