### ISSUE TITLE
Use siren as home document with links only

### ISSUE THREAD

**Issue by AlexZeitler** [kevinswiber/siren#59]
Is it designated to have a siren response having links only to be used a home document (similar to / as a replacement for [JSON Home](http://tools.ietf.org/html/draft-nottingham-json-home-02))?

**Comment by kevinswiber** [comment]
Sure, that's no problem. Often, I find myself also adding search actions to home documents (find-user, lookup-order, etc.). Using a class of "root" or "home" is something I do, as well, as most of my Siren client code reacts to the current representation by keying off classes (e.g., mapping a view to a class).

**Comment by AlexZeitler** [comment]
Thanks
