### ISSUE TITLE
Mix of Success and Failure - Reporting Associated Errors

### ISSUE THREAD

**Issue by wooliet** [kevinswiber/siren#61]
I'm looking for some guidance on formatting a correct response for the following scenario:

A new entity has been successfully created. However, there were errors associated with its creation, and the user should be made aware.

I would like to fill in the entities array as usual, but also include something indicating there were issues and provide a collection of error messages. **Is there a recommended response format for this situation?**

**Comment by apsoto** [comment]
@wooliet this is better discussed on the [Google Group](https://groups.google.com/forum/#!forum/siren-hypermedia)

In my experience, I haven't come across a partial success response.  The closest I've come to it is returning a [203 status](http://httpstatus.es/203).  In that case I added a 'warning' header to the regular 200 response.

If you want to provide some entities that are the error messages, check out the discussion here #5

**Comment by wooliet** [comment]
Thanks @apsoto, a new thread has been created here:
https://groups.google.com/forum/#!topic/siren-hypermedia/P93zreIxfMI
