### ISSUE TITLE
Assign a digital object identifier (DOI) to the specification

### ISSUE THREAD

**Issue by thomaseizinger** [kevinswiber/siren#83]
GitHub allows code to be easile cited through the use of DOIs. Here is a guide how to do that: https://guides.github.com/activities/citable-code/

This would greatly simplifies academic research that involves citing a specification (draft) like this one.

Is there any chance that this happens in the near future? I guess it would not take too long to set it up :)

**Comment by kevinswiber** [comment]
@thomaseizinger Done!

**Comment by thomaseizinger** [comment]
Cool! Thanks :)
