### ISSUE TITLE
Thoughts on encoding information in `class` entries

### ISSUE THREAD

**Issue by thomaseizinger** [kevinswiber/siren#96]
We have the usecase of returning actions to the client that are not yet available. More concretely, the server has a timestamp X by when it will make that action available.

We thought of using a `class` entry like `unavailable_until:X` where X is a unix timestamp. The reason we would like to include the action in a "disabled" state is so that the client can still show it to the user but in a disabled state. I'd say it is good practise to tell a user why something is disabled, that is why we would want to embed the timestamp as well.

However, the whole solution feels a bit hacky but I couldn't think of any other way to model that but still being compliant with the spec.

Anyone got experience in modelling such a requirement? What are the thoughts on modelling `class` entries like this?

**Comment by kevinswiber** [comment]
Hey @thomaseizinger,

The specification doesn't prevent using `class` in this way, so it's totally valid.

Another option is to take a more reactive approach.  You can use a class value of `disabled`, allowing the server to still handle requests by responding with a 503 Service Unavailable status and a `Retry-After` header.

Keep in mind that temporal or transitive class values may have an impact on freshness lifetime for caching.

**Comment by thomaseizinger** [comment]
Thanks for the clarifying response!

> Another option is to take a more reactive approach. You can use a class value of disabled, allowing the server to still handle requests by responding with a 503 Service Unavailable status and a Retry-After header.

That could be tricky in our case since the action may have fields and therefore require user input. It is an interesting idea nevertheless. I've never had a deeper look on the 5xx range of status codes for web APIs. Seems like I should :)

> Keep in mind that temporal or transitive class values may have an impact on freshness lifetime for caching.

Thanks for the pointer. Luckily, this shouldn't be an issue in our case!
